### PR TITLE
feat: Added support for ephemeral storage (requires AWS provider version 4.8.0)

### LINKED ISSUE #290: Add ephemeral_storage attribute to Lambda module
## Is your request related to a new offering from AWS?
AWS introduced support for Ephemeral storage size configuration to Lambda functions.

### References
- Announcement: https://aws.amazon.com/about-aws/whats-new/2022/03/aws-lambda-configure-ephemeral-storage/
- API: https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-EphemeralStorage
- Blog post: https://aws.amazon.com/blogs/aws/aws-lambda-now-supports-up-to-10-gb-ephemeral-storage/

The new feature is currently in PR in the AWS provider for Terraform - https://github.com/hashicorp/terraform-provider-aws/pull/23873, the new feature will be added to Terraform after the following PR is merged.

## Describe the solution you'd like.
Add a new field named "ephemeral_storage" that will configure the lambda function `ephemeral_storage`.

### PR DESCRIPTION
**Pull request by liortct**
## Description
Add support for configuring ephemeral storage size (/tmp file system) for lambda.

The changes include:
- Upgrade AWS provider version to 4.8.0, which introduces support for the ephemeral storage size configuration feature.
- Add a variable called `ephemeral_storage_size` and use this value in the main.tf.
- Replace deprecated resource aws_s3_bucket_object to aws_s3_object.
- Add an example for using the `ephemeral_storage_size` configuration.

## Motivation and Context
The ephemeral storage configuration is a new feature in AWS lambda. I would like to be able to use this feature via Terraform.

Fixes #290

## Breaking Changes
- The Terffaform AWS provider version must be upgraded from >=3.6.9 to >=4.8.0.
This upgrade is required as the `ephemeral_storage` configuration is added in version 4.8.0 of the AWS provider plugin - hashicorp/terraform-provider-aws#23873.
- Additionally I changed every use of `aws_s3_bucket_object` to `aws_s3_object` because `aws_s3_bucket_object` is deprecated - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object.

## How Has This Been Tested?
I have added a new exame for this feature at `example/ephemeral-storage` that uses the new feature.
I have tested the new change via the `terraform validate` command.

### CODE REVIEW

**Review by antonbabenko — CHANGES_REQUESTED** [review]
Good and quick one! Please remove the example folder you added but add just one argument (`ephemeral_storage_size = 10240`) to `examples/complete/main.tf` in module `lambda_function`.

**Comment by liortct** [comment]
@antonbabenko 

> Good and quick one! Please remove the example folder you added but add just one argument (`ephemeral_storage_size = 10240`) to `examples/complete/main.tf` in module `lambda_function`.

Done

**Comment by antonbabenko** [comment]
Merging like this. The feature is working as expected but currently `examples/complete` is failing due to the S3 bucket module is not being compatible with AWS provider v4 (https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/pull/139).

**Comment by antonbabenko** [comment]
This PR is included in version 2.37.0 :tada:

**Comment by jaikanthjay46** [comment]
@antonbabenko People's scripts are going to break even if they have pinned this to `~> 2` . Not all modules have updated to support provider v4. 

Since its a breaking change, it could have been timed better or released as a major version (v3.0.0)

**Comment by antonbabenko** [comment]
@jaikanthjay46 Good point! I missed this yesterday. I will make a major release instead.

**Comment by antonbabenko** [comment]
This PR is included in version 2.37.0 :tada:

**Comment by antonbabenko** [comment]
This PR is included in version 3.0.0 :tada:

**Comment by jaikanthjay46** [comment]
Thanks @antonbabenko, appreciate your rapid response 🥳 . You have single handedly stopped a StackOverflow exodus from happening.

**Pull request merged**
