### PR TITLE
chore: update documentation based on latest `terraform-docs` which includes module and resource sections

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Description
- update documentation based on latest `terraform-docs` which includes module and resource sections
- `.gitignore` updated using GitHub provided default standard + 0.14 lockfile ignore

## Motivation and Context
- these are two new sections provided by [`terraform-docs` now](https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.0)

## Breaking Changes
No

## How Has This Been Tested?
N/A

### CODE REVIEW

**Comment by antonbabenko** [comment]
I see that my `terraform-docs` decided to reorder couple of elements now. I think it is correct that datasources are coming before resources.

```
$ terraform-docs --version                  

terraform-docs version v0.11.0 darwin/amd64 BuildDate: 2021-02-11T00:17:03+0000
```

**Comment by antonbabenko** [comment]
Something weird is going on with this :)

I see that it is actually trying to update the same file multiple times because the order is not consistent.

```
# on master branch
 pre-commit run -a --verbose terraform_docs
Terraform docs...........................................................Failed
- hook id: terraform_docs
- duration: 2.43s
- files were modified by this hook
```

`aws_iam_role` resource and data-source are swapping the positions every time I rerun the command.

Maybe there should be some extra flag passed to `terraform-docs`?

**Comment by bryantbiggs** [comment]
ah, looks like a small bug. hopefully a patch release is sent out soon https://github.com/terraform-docs/terraform-docs/issues/393

**Comment by bryantbiggs** [comment]
looks like this might be solved now if you update to the latest @antonbabenko https://github.com/terraform-docs/terraform-docs/releases/tag/v0.11.1

**Comment by antonbabenko** [comment]
Thanks! Yes, now it works.

Should I also update docs in all of your similar PRs? Or are those already correct if I use 0.11.1?

**Comment by bryantbiggs** [comment]
@antonbabenko I just went through them yesterday evening to re-run `pre-commit run -a` so I *think they should correct (I hope). There were a few that did update, and a few that did not

**Comment by antonbabenko** [comment]
Great work! I will merge them later today/tomorrow.

**Pull request merged**
