### PR TITLE
fix: AttributeError os.exists is not valid python attribute.

### PR DESCRIPTION
**Pull request by lociko**
## Description
Fixed an attribute error made by typo

## Motivation and Context
This is an error - should be fixed

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [ ] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by code-intensive** [comment]
This typo has caused several of my CI/CD pipelines to fail.
Would be good to resolve the one-liner as soon as possible.

**Review by pdecat — APPROVED** [review]
Oops, LGTM !

**Review by pdecat — APPROVED** [review]

**Comment by pdecat** [comment]
Please update the PR title so checks can pass.

**Comment by lociko** [comment]
> Please update the PR title so checks can pass.

Done

**Comment by pdecat** [comment]
Hi @antonbabenko, can you merge this? 🙏

**Review by code-intensive — COMMENTED** [review]
This fix is clear and straightforward. Could someone with permission to approve kindly provide their approval?

**Comment by pdecat** [comment]
@antonbabenko Here we go https://github.com/terraform-aws-modules/terraform-aws-lambda/pull/555

**Comment by antonbabenko** [comment]
This PR is included in version 7.2.5 :tada:

**Pull request merged**
