### PR TITLE
feat: Make `compatible_runtimes` optional, added sam metadata control 

### PR DESCRIPTION
**Pull request by ajschmidt8**
## Description

This PR makes the `compatible_runtimes` argument for the `aws_lambda_layer_version` resource optional.

## Motivation and Context

Currently, the `compatible_runtimes` value is inferred from `var.compatible_runtimes` and `var.runtime`.

If neither of these values is set, the module throws an error.

I'm trying to use this module to publish a Lambda layer that doesn't depend on any particular runtime (it's just a plain-text configuration file).

Therefore, I'd expect that I'd be able to publish this layer without having to specify a runtime.

The official `aws_lambda_layer_version` resource docs mention that this argument is optional (see [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_layer_version#compatible_runtimes)), so I'd expect that it would be optional in this module as well.

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [x] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by ajschmidt8** [comment]
@antonbabenko, can you take a look at this when you have a moment?

**Comment by ajschmidt8** [comment]
this is not stale.

@antonbabenko, can you check on this PR soon?

**Review by antonbabenko — APPROVED** [review]
Looks great! Thank you!

**Comment by antonbabenko** [comment]
This PR is included in version 6.2.0 :tada:

**Pull request merged**
