### PR TITLE
fix: Override docker entrypoint when it exists

### LINKED ISSUE #313: Layer build error for python3.9
## Description

Getting `entrypoint requires the handler name to be the first argument` while trying to build the lambda layer via docker with python3.9 as runtime. Weird enough it works with python3.8, so im not sure whats missing here...

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 3.2.0
- Terraform version: v0.15.1
- MacOS: 12.1 running M1

- Provider version(s):
```
- Installed hashicorp/null v3.1.1 (signed by HashiCorp)
- Installed hashicorp/aws v4.14.0 (signed by HashiCorp)
- Installed hashicorp/archive v2.2.0 (signed by HashiCorp)
- Installed hashicorp/external v2.2.2 (signed by HashiCorp)
- Installed hashicorp/local v2.2.2 (signed by HashiCorp)
```

## Reproduction Code [Required]

```
module "lambda_layer" {
  source = "terraform-aws-modules/lambda/aws"
  version = "3.2.0"

  create_function     = false
  create_layer        = true
  layer_name          = "helloworld-layer"
  compatible_runtimes = ["python3.9"]
  runtime             = "python3.9"

  source_path = [
    {
      path             = "${path.module}/src"
      pip_requirements = true
      prefix_in_zip    = "python" # required to get the path correct
    }
  ]

  build_in_docker = true
  docker_image    = "public.ecr.aws/sam/build-python3.9"
  docker_file     = "${path.module}/src/Dockerfile"
}
```

```
# ${path.module}/src/Dockerfile

FROM public.ecr.aws/lambda/python:3.9

COPY requirements.txt  .
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

CMD ["index.handler"]
```

```
terraform init
terraform plan
terraform apply --auto-approve
```

## Expected behavior

docker run should behave correctly

```
docker run --rm -w /var/task
-v /private/var/folders/dd/fvl7_qz94f34p57zmsgzycth0000gn/T/terraform-aws-lambda-6u_93uta:/var/task:z
-v /Users/mratheist/.ssh/known_hosts:/root/.ssh/known_hosts:z 494788200de1 
/bin/sh -c 'python3.9 -m pip install --no-compile --prefix= --target=. --requirement=requirements.txt && chown -R 501:20 .'
```
### Terminal Output Screenshot(s)

```
# folder dir is loosely obfuscated... 

Error: Error running command 'builds/4596cd1b10d43761d40b1f13167df4a0f06830146de508936b3da4e345ef0c38.plan.json': exit status 1. Output: zip: creating 'builds/4596cd1b10d43761d40b1f13167df4a0f06830146de508936b3da4e345ef0c38.zip' archive
│ > docker images '--format={{.ID}}' public.ecr.aws/sam/build-python3.9
│ Installing python requirements: ../../modules/lambda-decrypt-kinesis/src/requirements.txt
│ > mktemp -d terraform-aws-lambda-XXXXXXXX # /var/folders/dd/fvl7_qz94f34p57zmsgzycth0000gn/T/terraform-aws-lambda-6u_93uta
│ > cd /var/folders/dd/fvl7_qz94f34p57zmsgzycth0000gn/T/terraform-aws-lambda-6u_93uta
│ > docker run --rm -w /var/task -v /private/var/folders/dd/fvl7_qz94f34p57zmsgzycth0000gn/T/terraform-aws-lambda-6u_93uta:/var/task:z -v /Users/mratheist/.ssh/known_hosts:/root/.ssh/known_hosts:z 494788200de1 /bin/sh -c 'python3.9 -m pip install --no-compile --prefix= --target=. --requirement=requirements.txt && chown -R 501:20 .'
│ entrypoint requires the handler name to be the first argument
│ zip: Error during zip archive creation
│ Traceback (most recent call last):
│   File ".terraform/modules/lambda_decrypt_kinesis.lambda_layer/package.py", line 1277, in build_command
│     bpm.execute(build_plan, zs, query)
│   File ".terraform/modules/lambda_decrypt_kinesis.lambda_layer/package.py", line 811, in execute
│     with install_pip_requirements(query, pip_requirements, tmp_dir) as rd:
│   File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 119, in __enter__
│     return next(self.gen)
│   File ".terraform/modules/lambda_decrypt_kinesis.lambda_layer/package.py", line 948, in install_pip_requirements
│     check_call(docker_run_command(
│   File "/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
│     raise CalledProcessError(retcode, cmd)
│ subprocess.CalledProcessError: Command '['docker', 'run', '--rm', '-w', '/var/task', '-v', '/private/var/folders/dd/fvl7_qz94f34p57zmsgzycth0000gn/T/terraform-aws-lambda-6u_93uta:/var/task:z', '-v', '/Users/mratheist/.ssh/known_hosts:/root/.ssh/known_hosts:z', '494788200de1', '/bin/sh', '-c', 'python3.9 -m pip install --no-compile --prefix= --target=. --requirement=requirements.txt && chown -R 501:20 .']' returned non-zero exit status 142.
```

### PR DESCRIPTION
**Pull request by micah5**
Fixes #313 

## Description
When a base image contains an entrypoint path, it'll cause an `entrypoint requires the handler name to be the first argument` error to be thrown as the current run commend doesn't override it.

## Motivation and Context
See issue #313. I am not sure when it happened, but the official AWS lambda runtime images started including entrypoints (lambci images still do not).

## Breaking Changes
Nope

## How Has This Been Tested?
Tested and working on my personal project. Official tests still todo:
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects
- [ ] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Comment by deybhayden** [comment]
Could we reopen this one and merge? I tested the change locally and it fixed building packages with the `public.ecr.aws/sam/build-pythonX` images.

**Comment by antonbabenko** [comment]
Hi Ben! Thank you for checking out this issue!

Please take this fresh release and confirm that it works for you as expected.

**Comment by antonbabenko** [comment]
This PR is included in version 4.0.2 :tada:

**Comment by deybhayden** [comment]
Great, thanks so much!

**Pull request merged**
